language: java
jdk:
- oraclejdk8
script: mvn clean package
addons:
  artifacts: true
deploy:
  provider: releases
  api_key:
    secure: hF2d8YyoKmHEVZA4XwYfwBtqZxomsg9s7/toGBiAX4sdWxr0pItyMqXykaaMkEHRn88WWmnzdQT7tSjfYDuWIpVf8yu510p1EJtnyCqSmkDqi1iS046axOJGcasGhSJNG7mHdQfwHhUkuLE4s91nCmVVxiwP+eXEG5Dq35rNITm5G0xxzxt1LT68zpqTX4U+xk+T0MZMlazSj+ZY3FuTgGG0YDypqTA+gf0E35wWIFKyQhqHnF6tMTT0IJ8c6A1bMWG35lLbJXhNz91SWVEgj7l0WfcukySMIYgccwyBxxBMjxCfURGpqAbRYBOAhOwQi1SDNaR3iuWVfU/Tukc+gDKtfSH5CD6egeJdnUD7G15MZZFkrgWSR1woak5Uf9raLF/boys2MjC5mNYdx3OCMWMhMJMfiMombT3SasNX8If1czVPykpxp9Hiw8DFwBrp/qH5VlbunVzCzEEfchLhjRdvcCBQ/kSC5nhmIleUKWPkfQwWCIQCVirL6qqvFKFYa+GP8g4SNtTjQc6Uga89fhHABBGXB1Dmr9jU6Ijk4mFZuV6U3K0+jYMQ+/X4v6wXJ//5Lp1ZQr8bl9o/ddRQ/eucx5K5jMVNMaWug72QFo8Ur51sHdr8slIdH4pMTIo2tgLorJyxpyKF5NT8RB8YvTjz82Fn2R/YjgqNgC/bIwI=
  file: target/*.jar
  skip_cleanup: true
  file_glob: true
  on:
    repo: Exorath/ExoBasePlugin